[package]
name = "webrtc_app"
version = "0.1.0"
edition = "2021"

[dependencies]
webrtc = "0.6"  # Replace with the correct version of webrtc-rs or your WebRTC library
tokio = { version = "1", features = ["full"] }
warp = "0.3"
futures-util = "0.3"
tracing = "0.1"
tokio-tungstenite = "0.16"
tracing-subscriber = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1", features = ["v4"] }





